learningtemplates/basicapp/urls.py
from django.urls import path
from django.conf.urls import url
from basicapp import views

# TEMPLATE TAGGING
app_name = 'basicapp'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

learningtemplates/learningtemplates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basicapp/', include('basicapp.urls')),
]

learningtemplates/basicapp/models.py
from django.db import models

# Create your models here.

learningtemplates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {'text':'Hello World!!', 'number':100}
    return render(request, 'basicapp/index.html', context)


def other(request):
    return render(request, 'basicapp/other.html')


def relative(request):
    return render(request, 'basicapp/relativeurltemplates.html')

learningtemplates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE.HTML</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}" class="navbar-brand">BRAND</a></li>
          <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
          <li><a href="{% url 'basicapp:other' %}" class="navbar-link">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited -->
      {% endblock %}
    </div>

  </body>
</html>

learningtemplates/templates/basicapp/index.html
<!DOCTYPE html>
{% load my_extras %}
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to INDEX.HTML</h1>
  </body>
</html> -->
{% extends 'basicapp/base.html' %}
  {% block body_block %}
    <h1>Welcome to INDEX.HTML</h1>
    <h2>This is an Example of TEMPLATE INHERITANCE</h2>
    <h1>{{text|cut:'hello'}}</h1>
    <h1>{{number|add:'99'}}</h1>
  {% endblock %}

learningtemplates/templates/basicapp/other.html
<!DOCTYPE html>
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to OTHER.HTML</h1>
  </body>
</html> -->
{% extends 'basicapp/base.html' %}
  {% block body_block %}
    <h1>Welcome to OTHER.HTML</h1>
    <h2>This is an Example of TEMPLATE INHERITANCE</h2>
  {% endblock %}

learningtemplates/templates/basicapp/relativeurltemplates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to RELATIVEURLTEMPLATES.HTML</h1>
    <a href="{% url 'basicapp:other' %}">OTHER.HTML</a>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a>
    <a href="{% url 'index' %}">INDEX.HTML</a>
  </body>
</html>